name: Update EPG
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  Update-EPG:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v3
        
      - name: checkout iptv-org/epg repo
        uses: actions/checkout@v3
        with:
         repository: iptv-org/epg
         path: iptv-org-epg

      - name: install XMLTV, URI::Encode and NPM
        run: sudo apt-get install -y xmltv liburi-encode-perl && npm install

      - name: update EPG
        run: sh EPG/epg-pt.sh

      - name: setup git config
        run: |
          git config user.name "ðŸ¤– R2-D2"
          git config user.email "<>"

      - name: commit
        run: |
          git pull
          cd EPG && git add .
          git commit -m "Update EPG"
          git push origin main
