name: Update streams
on:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  Update-streams:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v4

      - name: update streams
        run: sh M3U/streams.sh

      - name: setup git config
        run: |
          git config user.name "ðŸš€ HAL 9000"
          git config user.email "<>"

      - name: commit
        run: |
          git pull
          cd M3U && git add *.m3u
          git commit -m "Update streams"
          git push origin main
